framework:
    router:
        # URL base per generar URLs en contextos no-HTTP (com comandes CLI)
        default_uri: 'http://localhost'

when@prod:
    framework:
        router:
            strict_requirements: null